### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by urmzd** [urmzd/lepus-classifier#23]
Depends on #25

**Comment by ksek87** [comment]
- [ ] Introduction (CNN image classifcation)
- [ ] Experimental Set-up/Structure of our Study
- [ ] Data Collection + Pre-Processing (Normalization, etc)
- [ ] Model Architecture Overview
- [ ] Experiments + Theoretical Background to match (At each step in notebook, model building)
- [ ] Discussion of Findings
- [ ] Conclusions (Further Opportunities and Key Takeaways)

**Comment by ksek87** [comment]
[report](docs/report-docs/lepus-classifier_report.pdf)
